services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3003:3000"
    restart: always
    env_file:
      - .env
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
      # JWTパスワードは32文字以上！
      PGRST_JWT_SECRET: zd84xm45JvOkYm6Tw9nxwJ9b7H4HDRPZ
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3003
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
#      - "./pgdata:/var/lib/postgresql/data"
      - "./initdb:/docker-entrypoint-initdb.d"

  db-gui:
    image: sosedoff/pgweb
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      PGWEB_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always
    environment:
      API_URL: http://localhost:3003/
